/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Chapters {
  created_at: string;
  id: Generated<number>;
  novel_id: number;
  number: number;
  status: Generated<string>;
  updated_at: string;
}

export interface Greetings {
  created_at: string;
  days: string | null;
  id: Generated<number>;
  message: string;
  time: string | null;
  updated_at: string;
}

export interface Novels {
  created_at: string;
  id: Generated<number>;
  last_error: string | null;
  name: string;
  slug: string;
  source_language: string;
  status: Generated<string>;
  total_chapters: number;
  updated_at: string;
}

export interface DB {
  chapters: Chapters;
  greetings: Greetings;
  novels: Novels;
}
