/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiActivityRouteImport } from './routes/api/activity'
import { Route as ApiNovelsRouteImport } from './routes/api/novels'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivityRoute = ApiActivityRouteImport.update({
  id: '/api/activity',
  path: '/api/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNovelsRoute = ApiNovelsRouteImport.update({
  id: '/api/novels',
  path: '/api/novels',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/novels': typeof ApiNovelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/novels': typeof ApiNovelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/novels': typeof ApiNovelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/activity' | '/api/novels'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/activity' | '/api/novels'
  id: '__root__' | '/' | '/api/activity' | '/api/novels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiActivityRoute: typeof ApiActivityRoute
  ApiNovelsRoute: typeof ApiNovelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activity': {
      id: '/api/activity'
      path: '/api/activity'
      fullPath: '/api/activity'
      preLoaderRoute: typeof ApiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/novels': {
      id: '/api/novels'
      path: '/api/novels'
      fullPath: '/api/novels'
      preLoaderRoute: typeof ApiNovelsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiActivityRoute: ApiActivityRoute,
  ApiNovelsRoute: ApiNovelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
